[package]
edition = "2024"
name = "brush"
version = "0.1.0"

[dependencies]
anyhow = "1.0.99"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.143"
rusqlite = { version = "0.37.0", features = ["bundled"] }